export const ActionTypes = {
  ADD_TO_WISHLIST: "ADD_TO_WISHLIST",
  REMOVE_FROM_WISHLIST: "REMOVE_FROM_WISHLIST",
  // REMOVE_ONE: "REMOVE_ONE",
  // SAVE_SHIPPING_INFO: "SAVE_SHIPPING_INFO",
};
